import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  content: {
    paddingHorizontal: 24,
    paddingBottom: 60,
    gap: 24,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  avatarWrapper: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: '#D7F1FF',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: '#0E52FF',
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  tagRow: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 12,
  },
  tagPill: {
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 14,
    backgroundColor: '#E7EEFF',
  },
  statsCard: {
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 24,
    gap: 18,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  statBlock: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#F0F4FF',
  },
  sectionCard: {
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 20,
    gap: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  listRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pill: {
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#F0F4FF',
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  actionButton: {
    flexBasis: '48%',
    backgroundColor: '#0E52FF',
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 16,
    gap: 10,
    shadowColor: '#0E52FF',
    shadowOpacity: 0.35,
    shadowRadius: 16,
  },
  actionSecondary: {
    backgroundColor: '#0B1F44',
    shadowColor: '#0B1F44',
  },
});
